server:
  port: 8090

spring:
  application:
    name: ware-jwt-token
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 0
    host: localhost
    timeout: 10000ms
#token:
#  expireTime:259200000
#  secretKey:abcdefghijklmnopqrstuvwxyz
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml

config:
  jwt:
    secretKey: qwertyuiopasdfghjklzxcvbnm
    expireTime: 259200000
